[[repos]]
repo = "local"
hooks = [
  {
    id = "ruff-format",
    name = "ruff format",
    language = "system",
    entry = "uv run ruff format",
    files = "\\.py$",
  },
  {
    id = "ruff",
    name = "ruff check",
    language = "system",
    entry = "uv run ruff check --fix",
    files = "\\.py$",
  },
  {
    id = "pytest",
    name = "pytest",
    language = "system",
    entry = "uv run pytest",
    pass_filenames = false,
  },
]
